# Simulate RI Logit

## Packages

In [2]:
import numpy as np

from src.simulation.simulate_logit import SimulateRILogit

## Global Parameters

In [57]:
J = 5 # Number of products
N = 3 # Number of states per products
llambda = 0.1 # Information Cost
I = 10 # Number of Individuals
n_sim = 1000 # Number of simulation for each individuals
state = (0, 1, 0, 2, 1)

## Simulate Individuals

for now we just pick individuals payoff and prior matrix  matrix. In the future to assess the performance of our estimators we will have to get payoff and prior matrix as function of individual characteristics and parameters $\theta \in \Theta$ to be estimated.

In [66]:
list_u_mat = [np.random.rand(N, J).round(2) for _ in range(I)] # Draws payoff matrix for each individuals
list_ppi = [np.array([np.random.dirichlet(np.ones(N)) for _ in range(J)]).T for _ in range(I)] # Draws prior matrix for each individuals

## Simulate Logit Choice

Using Blahut–Arimoto solver

In [67]:
list_classes_BA = [
    SimulateRILogit(u_mat=u_mat, ppi=ppi, llambda=llambda)
    for u_mat, ppi in zip(list_u_mat, list_ppi)
]
list_indexes_BA = [cl.get_states().index(state) for cl in list_classes_BA]
list_choices_BA = [cl.simulate(n_sim=n_sim, states=state) for cl in list_classes_BA]
list_dist_BA = [cl.get_logit()[index] for cl, index in zip(list_classes_BA, list_indexes_BA)]

Blahut–Arimoto Solver:   0%|          | 13/10000 [00:00<00:05, 1687.27iter/s, Error=[3.61442327e-13]]


In [68]:
list_dist_BA[4]

array([8.88979070e-01, 0.00000000e+00, 7.09699551e-02, 4.00509746e-02,
       2.76821908e-16])

In [69]:
list_classes_SQP = [
    SimulateRILogit(u_mat=u_mat, ppi=ppi, llambda=llambda, method="SQP")
    for u_mat, ppi in zip(list_u_mat, list_ppi)
]
list_indexes_SQP = [cl.get_states().index(state) for cl in list_classes_SQP]
list_choices_SQP = [cl.simulate(n_sim=n_sim, states=state) for cl in list_classes_SQP]
list_dist_SQP = [cl.get_logit()[index] for cl, index in zip(list_classes_SQP, list_indexes_SQP)]

SQP Solver:   0%|          | 0/10000 [00:00<?, ?iter/s]


Warning algorithm did not converge


SQP Solver:   0%|          | 0/10000 [00:00<?, ?iter/s]


Warning algorithm did not converge


SQP Solver:   0%|          | 1/10000 [00:00<00:51, 195.89iter/s, Error=4.01e-24]


In [72]:
list_dist_SQP[4]

array([0.88900512, 0.        , 0.07094736, 0.04004752, 0.        ])

In [74]:
list_choices_SQP[4][1]

array([[0.869, 0.   , 0.085, 0.046]])